name: Build and Push Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        required: true

jobs:
  build-and-push:
  
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set tag name
      id: tag_name
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
        elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "::set-output name=tag::${{ github.event.inputs.tag }}"
        fi

    - name: Build and push Docker image with Release tag
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          deepseek-free-api:${{ steps.tag_name.outputs.tag }}
        platforms: linux/amd64,linux/arm64
        build-args: TARGETPLATFORM=${{ matrix.platform }}
